-- ============================================================
--  QR Registration System — PostgreSQL (Supabase) Schema
--  Run this in your Supabase SQL Editor
-- ============================================================

-- Drop tables if they exist (Be careful with real data!)
-- DROP TABLE IF EXISTS registrations;
-- DROP TABLE IF EXISTS guests;

-- Guest list imported from Excel
CREATE TABLE IF NOT EXISTS guests (
    id             VARCHAR(30)  PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    department     VARCHAR(255) DEFAULT '',
    job_title      VARCHAR(255) DEFAULT '',
    table_number   VARCHAR(50)  DEFAULT '',
    gmail          VARCHAR(255) DEFAULT '',
    created_at     TIMESTAMPTZ  DEFAULT NOW()
);

-- Scan / check-in log
CREATE TABLE IF NOT EXISTS registrations (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id        VARCHAR(30)  DEFAULT NULL,      -- internal row id
    guest_id       VARCHAR(30)  DEFAULT NULL,      -- links to guests.id (NULL for walk-ins)
    scan_data      VARCHAR(500) NOT NULL,           -- name or raw QR text
    department     VARCHAR(255) DEFAULT '',
    table_no       VARCHAR(50)  DEFAULT '',
    timestamp      VARCHAR(100) NOT NULL,           -- human-readable locale string
    created_at     TIMESTAMPTZ  DEFAULT NOW(),
    CONSTRAINT fk_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE SET NULL
);

-- Indexing for faster lookups (Optional but recommended)
CREATE INDEX IF NOT EXISTS idx_guests_name ON guests(name);
CREATE INDEX IF NOT EXISTS idx_registrations_scan_id ON registrations(scan_id);
CREATE INDEX IF NOT EXISTS idx_registrations_guest_id ON registrations(guest_id);
